import Head from "next/head";
import Image from "next/image";
import AdminDashboard from "../components/AdminDashboard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Scribbes-admin-pannel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <AdminDashboard />
      </div>
    </>
  );
}
